# Generated by Django 4.2.7 on 2026-06-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(choices=[('bi-cart', 'Shopping'), ('bi-house', 'Housing'), ('bi-car-front', 'Transport'), ('bi-heart-pulse', 'Health'), ('bi-mortarboard', 'Education'), ('bi-film', 'Entertainment'), ('bi-cup-hot', 'Food & Drinks'), ('bi-lightning', 'Utilities'), ('bi-briefcase', 'Salary'), ('bi-graph-up', 'Investment'), ('bi-gift', 'Gifts'), ('bi-airplane', 'Travel'), ('bi-phone', 'Phone'), ('bi-controller', 'Gaming'), ('bi-book', 'Books'), ('bi-scissors', 'Personal Care'), ('bi-three-dots', 'Other'), ('bi-cash-coin', 'Business'), ('bi-piggy-bank', 'Savings'), ('bi-star', 'Miscellaneous')], default='bi-three-dots', max_length=50),
        ),
    ]
