# Generated by Django 4.2.7 on 2026-06-15 16:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0002_alter_category_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#6366f1', max_length=7)),
                ('icon', models.CharField(choices=[('bi-basket', 'Essentials'), ('bi-emoji-smile', 'Lifestyle'), ('bi-house-heart', 'Home'), ('bi-airplane', 'Travel'), ('bi-piggy-bank', 'Savings'), ('bi-heart-pulse', 'Health'), ('bi-mortarboard', 'Education'), ('bi-stars', 'Discretionary'), ('bi-collection', 'General')], default='bi-collection', max_length=50)),
                ('monthly_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Optional shared cap across all member categories.', max_digits=15, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_type', models.CharField(choices=[('category', 'Category'), ('overall', 'Overall Monthly')], default='category', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('alert_threshold', models.PositiveSmallIntegerField(default=80, help_text='Warn when spending reaches this percentage of the limit.')),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='transactions.category')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets', to='budgets.budgetgroup')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(condition=models.Q(('budget_type', 'category'), ('is_active', True)), fields=('category',), name='unique_active_category_budget'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(condition=models.Q(('budget_type', 'overall'), ('is_active', True)), fields=('budget_type',), name='unique_active_overall_budget'),
        ),
    ]
